**Data Mining With Human Mobility Data**

**Introduction**

This project attempts to use human mobility data to find Co-occurrence Patterns of Points of Interest. This can be used for tourism and to find co-relation between places.

In [1]:
# Imports

import pandas as pd
import numpy as np

In [2]:
df_cityB_POI = pd.read_csv("/workspaces/Machine-learning-projects/JapanDataMining/Data/POIdata_cityB.csv")
df_cityC_POI = pd.read_csv("/workspaces/Machine-learning-projects/JapanDataMining/Data/POIdata_cityC.csv")
df_cityD_POI = pd.read_csv("/workspaces/Machine-learning-projects/JapanDataMining/Data/POIdata_cityD.csv")

In [6]:
df_cityD_POI.head() # Sample look into how these data frames look

   x   y  category  POI_count
0  1  11        46          1
1  1  55        60          2
2  1  55        48          1
3  1  56        68          1
4  1  56        75          1

In [7]:
df_cityB_challenge = pd.read_csv("/workspaces/Machine-learning-projects/JapanDataMining/Data/cityB_challengedata.csv/hiroshima_challengedata.csv")

In [8]:
df_cityB_challenge

            uid   d   t    x    y
0             0   0  20   80   99
1             0   0  21   81   97
2             0   0  25   83  102
3             0   0  26   80  101
4             0   0  27   80  101
...         ...  ..  ..  ...  ...
24375893  24999  74  36  999  999
24375894  24999  74  37  999  999
24375895  24999  74  39  999  999
24375896  24999  74  43  999  999
24375897  24999  74  47  999  999

[24375898 rows x 5 columns]

In [10]:
df_cityB_challenge.shape

(24375898, 5)